# Checks for the label 'chota' in the issue
- name: Check for "chota" label
  ...

# Checks out code from the repository
- name: Checkout code
  ...

# Checks if a branch exists
- name: Check if branch exists
  ...

# Create a new branch if it doesn't exist
- name: Creating or switching branch
  ...

# Switches to the existing branch
- name: Switching to existing branch
  ...

# Pushes the branch to the remote repository
- name: Push branch
  ...

# Updates the comment status to 'Running'
- name: Update comment to Running
  ...

# Installs Node.js
- name: Install Node.js
  ...

# Executes the Chota script
- name: Run Chota
  ...

# Checks for changes and comments if there are updates
- name: Check for changes and comment if there are updates
  ...

# Commits and pushes changes to the branch
- name: Commit and push branch
  ...

# Updates the comment status to 'Completed'
- name: Update comment to Completed
  ...