on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install @actions/github
      - name: Run Script
        run: node index.js